[package]
name = "midnight-installer"
description = "Installer for Midnight Foundation federated-node-operator (FNO) hosts"
version = "0.2.0"
edition = "2021"
resolver = "2"
license = "Apache-2.0"

[[bin]]
name = "midnight-installer"
path = "src/bin/midnight-installer.rs"

[dependencies]
installer = { git = "https://github.com/swimming-bookstore/installer" }
anyhow = { version = "1", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
clap = { version = "4", features = ["std", "color", "usage", "help", "error-context", "suggestions", "derive", "env"] }
nix = { version = "0.29", default-features = false, features = ["user", "fs", "process", "hostname"] }
serde = { version = "1", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["process", "fs", "signal", "tracing", "rt-multi-thread", "macros", "io-util"] }
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "registry", "fmt", "json", "ansi", "env-filter"] }
typetag = { version = "0.2", default-features = false }
url = { version = "2", default-features = false, features = ["serde"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
opt-level = "z"
lto = true
