[package]
name = "midnight-installer"
description = "Installer for Midnight Foundation federated-node-operator (FNO) hosts"
version = "0.2.0"
edition = "2021"
resolver = "2"
license = "Apache-2.0"

[[bin]]
name = "midnight-installer"
path = "src/bin/midnight-installer.rs"

[dependencies]
anyhow = { version = "1", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
clap = { version = "4", features = ["std", "color", "usage", "help", "error-context", "suggestions", "derive", "env"] }
dyn-clone = { version = "1", default-features = false }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
nix = { version = "0.29", default-features = false, features = ["user", "fs", "process", "hostname"] }
owo-colors = { version = "4", default-features = false, features = ["supports-colors"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-native-roots"] }
rpassword = { version = "7", default-features = false }
semver = { version = "1", default-features = false, features = ["serde", "std"] }
serde = { version = "1", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
sha2 = { version = "0.10", default-features = false }
tar = { version = "0.4", default-features = false }
tokio = { version = "1", default-features = false, features = ["process", "fs", "signal", "tracing", "rt-multi-thread", "macros", "io-util"] }
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "registry", "fmt", "json", "ansi", "env-filter"] }
typetag = { version = "0.2", default-features = false }
url = { version = "2", default-features = false, features = ["serde"] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[profile.release]
strip = true
opt-level = "z"
lto = true
